### ISSUE TITLE
Minor stying tweaks across core blocks

### ISSUE THREAD

**Issue by JohnPixle** [Codeinwp/neve-fse#13]
Hey @preda-bogdan 

I collected some issues across core blocks and posting here for your attention. 
I used these blocks[ **in this page**](https://fse-neve.vertisite.cloud/components/) as well, for your convenience.

Below are the key points:

## Calendar Block

- [x] The calendar block needs some help with the colors, we need to map them to our palette. I am giving you code snippets below in case they help.

```css
/* Border color of calendar should inherit ti-bg-alt color */

.wp-block-calendar td, .wp-block-calendar th {
    border: 1px solid var(--wp--preset--color--ti-bg-alt);
    padding: 8px;
}

:where(.wp-block-calendar table:not(.has-background) th)
{
border-color: 1 px solid var(--wp--preset--color--ti-bg-alt);
}

/* Text of calendar should inherit ti-fg color */

.wp-block-calendar table:where(:not(.has-text-color)){
color: var(--wp--preset--color--ti-fg);
}

/*Set bg color of calendar header to bg-inv */

:where(.wp-block-calendar table:not(.has-background) th)
{
background-color: var(--wp--preset--color--ti-bg-inv);
}
```

## Latest posts block

- [x] This is about the latest posts block, just some sizing and decoration tweaks.

![Screenshot 2023-04-07 at 1 17 33 PM-1](https://user-images.githubusercontent.com/4193672/230602775-416ff68a-2ef5-4671-9920-564e3834165e.png)

```css

/* Set post titles to default size and remove underline, set bottom margin to 8px */

.wp-block-latest-posts .wp-block-latest-posts__post-title { 
display: block; 
font-size: var(--wp--preset--font-size--normal); 
font-weight: 600; 
margin-bottom: 8px; 
text-decoration: none;

/* Set bottom margin to list items */

.wp-block-latest-posts.wp-block-latest-posts__list li {
margin-bottom:16px;
}

```

## Consistent look for Terms: Categories and tags (and tag cloud)

- [x] We want the same pill shape for the Categories and the tags. If you can fix the alignment of the suffix and the prefix as well, it would be great.

![Screenshot 2023-04-07 at 1 25 59 PM](https://user-images.githubusercontent.com/4193672/230602821-247a40a3-3a76-4eba-9d76-657765e663c7.png)

- [x] Ideally we’d want the same style to be applied to the tag cloud block
![Screenshot 2023-04-07 at 2 24 01 PM](https://user-images.githubusercontent.com/4193672/230602834-a990b9eb-678a-4d2c-bdfe-8a6e0e6414e5.png)

## Block Quote
![Screenshot 2023-04-07 at 2 28 38 PM](https://user-images.githubusercontent.com/4193672/230602912-ad235709-2b0f-43f3-8ad3-7b0e32f68e9b.png)

- [x] For block quote, we’d need the Citation to be normal font size. The quote text itself is fine.

## Search

- [x] Can we have the placeholder / input text inherit the normal text size?
![Screenshot 2023-04-07 at 2 32 28 PM](https://user-images.githubusercontent.com/4193672/230602957-5499fdb2-6a9f-4971-9cbb-95f0a99ac236.png)

--- 

Thanks in advance for the help, let me know if you need any clarifications on these ones!
